SELECT 
    TABLE_NAME AS 'Ten_Bang', 
    COLUMN_NAME AS 'Ten_Cot', 
    COLUMN_TYPE AS 'Kieu_Du_Lieu',
    IS_NULLABLE AS 'Cho_Phep_Null',
    COLUMN_KEY AS 'Loai_Khoa'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'QLBH'
ORDER BY TABLE_NAME, ORDINAL_POSITION;